### PR TITLE
almost final

### PR DESCRIPTION
**Pull request by HumpyBlumpy**
Finished theme.
Added print_friends and checks to ensure non-users dont get added(as well as the same user twice or logged in user)

### CODE REVIEW

**Comment by jofwolves** [comment]
Two requests before merging everything:
- It would be nice to be able to see one’s own topics (previously I’d been hacking this by just adding myself to my own friend list; I like the idea of making that impossible though); it should be as simple as a `friend_list.append(u_name)` or something along those lines at the top of the `print_topics()` function
- for general privacy reasons, `make chmod` should probably ignore the actual code files (Login.c, Register.pl, MyFacebookPage.py); either that or just set them to 700—same goes for images and whatnot; all people really need access to is the html pages and the executables

**Comment by HumpyBlumpy** [comment]
First point: We could add it but should we? The assignment says "The 10 most recent messages from friends."
Regarding the makefile: yea you are right. I was just being lazy. Although images need rx I think.

The table doesn't have a finite amount of lines AFAIK, it just expands as needed(so yea scrolling). I tested by adding many topics.

**Comment by jofwolves** [comment]
I guess you’re right, there’s no need to see one’s own topics. It was nice during the testing phase, but there’s not much actual use in it. Scratch that, then.

Sounds good re: everything else

**Comment by HumpyBlumpy** [comment]
I fixed the makefile and cleaned up a bit but it doesnt update the pull request for some reason.

**Comment by jofwolves** [comment]
Generally anything you push to the branch that's on the pull request should automagically be a part of it, so I'm gonna go ahead and merge it. I've never done this on Github before, but that's how it would work on Gitlab, and they seem to mostly be the same, so…

**Pull request merged**
